import 'package:flutter/material.dart';
import 'package:trial_mobile/models/abakada_model.dart';

import 'package:trial_mobile/models/hayop_model.dart';
import 'package:trial_mobile/models/pangungusap_model.dart';
import 'package:trial_mobile/models/parirala_model.dart';
import 'package:trial_mobile/models/salita_model.dart';
import 'package:trial_mobile/models/things_model.dart';

import 'package:trial_mobile/utils/assets_path.dart';

import '../models/alpabeto_model.dart';

class AppConstants {
  static List<Hayop> animalsItem = [
    Hayop(
      name: 'Pusa',
      svgAsset: AssetsPath.getAnimalImage(Animals.cat),
      soundAsset: AssetsPath.getAnimalSound(Animals.catSound),
      speechAsset: AssetsPath.getAnimalSound(Animals.pusaSound), //
      backgroundColor: const Color.fromARGB(193, 76, 175, 79),
    ),
    Hayop(
      name: 'Usa',
      svgAsset: AssetsPath.getAnimalImage(Animals.deer),
      soundAsset: AssetsPath.getAnimalSound(Animals.deerSound),
      speechAsset: AssetsPath.getAnimalSound(Animals.usaSound),
      backgroundColor: const Color.fromARGB(194, 157, 82, 222),
    ),
    Hayop(
      name: 'Oso',
      svgAsset: AssetsPath.getAnimalImage(Animals.bear),
      soundAsset: AssetsPath.getAnimalSound(Animals.bearSound),
      speechAsset: AssetsPath.getAnimalSound(Animals.osoSound),
      backgroundColor: const Color.fromARGB(193, 76, 207, 222),
    ),
    Hayop(
      name: 'Baka',
      svgAsset: AssetsPath.getAnimalImage(Animals.cow),
      soundAsset: AssetsPath.getAnimalSound(Animals.cowSound),
      speechAsset: AssetsPath.getAnimalSound(Animals.bakaSound),
      backgroundColor: const Color.fromARGB(157, 251, 0, 0),
    ),
    Hayop(
      name: 'Baboy',
      svgAsset: AssetsPath.getAnimalImage(Animals.pig),
      soundAsset: AssetsPath.getAnimalSound(Animals.pigSound),
      speechAsset: AssetsPath.getAnimalSound(Animals.baboySound),
      backgroundColor: const Color.fromARGB(151, 40, 137, 248),
    ),
    Hayop(
      name: 'Tupa',
      svgAsset: AssetsPath.getAnimalImage(Animals.sheep),
      soundAsset: AssetsPath.getAnimalSound(Animals.sheepSound),
      speechAsset: AssetsPath.getAnimalSound(Animals.tupaSound),
      backgroundColor: const Color.fromARGB(193, 240, 241, 170),
    ),
    Hayop(
      name: 'Ahas',
      svgAsset: AssetsPath.getAnimalImage(Animals.snake),
      soundAsset: AssetsPath.getAnimalSound(Animals.snakeSound),
      speechAsset: AssetsPath.getAnimalSound(Animals.ahasSound),
      backgroundColor: const Color.fromARGB(193, 125, 176, 127),
    ),
    Hayop(
      name: 'Aso',
      svgAsset: AssetsPath.getAnimalImage(Animals.dog),
      soundAsset: AssetsPath.getAnimalSound(Animals.dogSound),
      speechAsset: AssetsPath.getAnimalSound(Animals.asoSound),
      backgroundColor: const Color.fromARGB(193, 33, 149, 243),
    ),
    Hayop(
      name: 'Elepante',
      svgAsset: AssetsPath.getAnimalImage(Animals.elephant),
      soundAsset: AssetsPath.getAnimalSound(Animals.elephantSound),
      speechAsset: AssetsPath.getAnimalSound(Animals.elepanteSound),
      backgroundColor: const Color.fromARGB(193, 182, 221, 252),
    ),
    Hayop(
      name: 'Leon',
      svgAsset: AssetsPath.getAnimalImage(Animals.lion),
      soundAsset: AssetsPath.getAnimalSound(Animals.lionSound),
      speechAsset: AssetsPath.getAnimalSound(Animals.leonSound),
      backgroundColor: Color.fromARGB(193, 116, 232, 120),
    ),
    Hayop(
      name: 'Kuneho',
      svgAsset: AssetsPath.getAnimalImage(Animals.rabbit),
      soundAsset: AssetsPath.getAnimalSound(Animals.rabbitSound),
      speechAsset: AssetsPath.getAnimalSound(Animals.kunehoSound),
      backgroundColor: const Color.fromARGB(156, 243, 33, 236),
    ),
    Hayop(
      name: 'Maya',
      svgAsset: AssetsPath.getAnimalImage(Animals.bird),
      soundAsset: AssetsPath.getAnimalSound(Animals.birdSound),
      speechAsset: AssetsPath.getAnimalSound(Animals.ibonSound),
      backgroundColor: const Color.fromARGB(193, 76, 175, 79),
    ),
  ];

  static List<Things> thingsItem = [
    Things(
      name: 'Upuan',
      svgAsset: AssetsPath.getThingsImages(Bagay.chair),
      soundAsset: AssetsPath.getThingsSound(Bagay.chairSound),
      backgroundColor: const Color.fromARGB(193, 76, 175, 79),
    ),
    Things(
      name: 'Aklat',
      svgAsset: AssetsPath.getThingsImages(Bagay.book),
      soundAsset: AssetsPath.getThingsSound(Bagay.bookSound),
      backgroundColor: const Color.fromARGB(194, 157, 82, 222),
    ),
    Things(
      name: 'Lamesa',
      svgAsset: AssetsPath.getThingsImages(Bagay.table),
      soundAsset: AssetsPath.getThingsSound(Bagay.tableSound),
      backgroundColor: const Color.fromARGB(193, 76, 207, 222),
    ),
    Things(
      name: 'Bola',
      svgAsset: AssetsPath.getThingsImages(Bagay.ball),
      soundAsset: AssetsPath.getThingsSound(Bagay.ballSound),
      backgroundColor: const Color.fromARGB(139, 175, 140, 76),
    ),
    Things(
      name: 'Saranggola',
      svgAsset: AssetsPath.getThingsImages(Bagay.kite),
      soundAsset: AssetsPath.getThingsSound(Bagay.kiteSound),
      backgroundColor: const Color.fromARGB(157, 251, 151, 0),
    ),
    Things(
      name: 'Orasan',
      svgAsset: AssetsPath.getThingsImages(Bagay.clock),
      soundAsset: AssetsPath.getThingsSound(Bagay.clockSound),
      backgroundColor: const Color.fromARGB(193, 76, 175, 79),
    ),
    Things(
      name: 'Lapis',
      svgAsset: AssetsPath.getThingsImages(Bagay.lapis),
      soundAsset: AssetsPath.getThingsSound(Bagay.pencilSound),
      backgroundColor: const Color.fromARGB(193, 182, 221, 252),
    ),
    Things(
      name: 'Sapatos',
      svgAsset: AssetsPath.getThingsImages(Bagay.sapatos),
      soundAsset: AssetsPath.getThingsSound(Bagay.shoesSound),
      backgroundColor: const Color.fromARGB(194, 157, 82, 222),
    ),
    Things(
        name: 'Baso',
        svgAsset: AssetsPath.getThingsImages(Bagay.baso),
        soundAsset: AssetsPath.getThingsSound(Bagay.glassSound),
        backgroundColor: const Color.fromARGB(194, 199, 175, 219)),
    Things(
      name: 'Gunting',
      svgAsset: AssetsPath.getThingsImages(Bagay.gunting),
      soundAsset: AssetsPath.getThingsSound(Bagay.scissorSound),
      backgroundColor: const Color.fromARGB(193, 182, 221, 252),
    ),
  ];

  static List<AbakadaData> abakadaItems = [
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ba),
      abakadaTitle: 'BA',
      abakadaDescription: 'agasd',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.baSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.be),
      abakadaTitle: 'BE',
      abakadaDescription: 'agasd',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.beSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.bi),
      abakadaTitle: 'BI',
      abakadaDescription: 'agasd',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.biSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.bo),
      abakadaTitle: 'BO',
      abakadaDescription: 'agasd',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.boSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.bu),
      abakadaTitle: 'BU',
      abakadaDescription: 'agasd',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.buSound),
    ),
       AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ka),
      abakadaTitle: 'KA',
      abakadaDescription: 'agasd',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.kaSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ke),
      abakadaTitle: 'KE',
      abakadaDescription: 'agasd',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.keSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ki),
      abakadaTitle: 'KI',
      abakadaDescription: 'agasd',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.kiSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ko),
      abakadaTitle: 'KO',
      abakadaDescription: 'agasd',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.koSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ku),
      abakadaTitle: 'KU',
      abakadaDescription: 'agasd',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.kuSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.da),
      abakadaTitle: 'DA',
      abakadaDescription: 'agasd',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.daSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.de),
      abakadaTitle: 'DE',
      abakadaDescription: 'agasd',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.deSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.di),
      abakadaTitle: 'DI',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.diSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.dod),
      abakadaTitle: 'DO',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.doSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.du),
      abakadaTitle: 'DU',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.duSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ga),
      abakadaTitle: 'GA',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.gaSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ge),
      abakadaTitle: 'GE',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.geSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.gi),
      abakadaTitle: 'GI',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.giSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.go),
      abakadaTitle: 'GO',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.goSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.gu),
      abakadaTitle: 'GU',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.guSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ha),
      abakadaTitle: 'HA',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.haSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.he),
      abakadaTitle: 'HE',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.heSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.hi),
      abakadaTitle: 'HI',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.hiSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ho),
      abakadaTitle: 'HO',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.hoSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.hu),
      abakadaTitle: 'HU',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.huSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.la),
      abakadaTitle: 'LA',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.laSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.le),
      abakadaTitle: 'LE',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.leSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.li),
      abakadaTitle: 'LI',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.liSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.lo),
      abakadaTitle: 'LO',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.loSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.lu),
      abakadaTitle: 'LU',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.luSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ma),
      abakadaTitle: 'MA',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.maSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.me),
      abakadaTitle: 'ME',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.meSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.mi),
      abakadaTitle: 'MI',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.miSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.mo),
      abakadaTitle: 'MO',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.moSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.mu),
      abakadaTitle: 'MU',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.muSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.na),
      abakadaTitle: 'NA',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.naSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ne),
      abakadaTitle: 'NE',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.neSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ni),
      abakadaTitle: 'NI',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.niSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.no),
      abakadaTitle: 'NO',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.noSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.nu),
      abakadaTitle: 'NU',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.nuSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.nga),
      abakadaTitle: 'NGA',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.ngaSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.nge),
      abakadaTitle: 'NGE',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.ngeSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ngi),
      abakadaTitle: 'NGI',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.ngiSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ngo),
      abakadaTitle: 'NGO',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.ngoSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ngu),
      abakadaTitle: 'NGU',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.nguSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.pa),
      abakadaTitle: 'PA',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.paSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.pe),
      abakadaTitle: 'PE',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.peSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.pi),
      abakadaTitle: 'PI',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.piSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.po),
      abakadaTitle: 'PO',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.poSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.pu),
      abakadaTitle: 'PU',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.puSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ra),
      abakadaTitle: 'RA',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.raSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.re),
      abakadaTitle: 'RE',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.reSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ri),
      abakadaTitle: 'RI',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.riSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ro),
      abakadaTitle: 'RO',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.roSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ru),
      abakadaTitle: 'RU',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.ruSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.sa),
      abakadaTitle: 'SA',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.saSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.se),
      abakadaTitle: 'SE',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.seSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.si),
      abakadaTitle: 'SI',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.siSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.so),
      abakadaTitle: 'SO',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.soSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.su),
      abakadaTitle: 'SU',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.suSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ta),
      abakadaTitle: 'TA',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.taSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.te),
      abakadaTitle: 'TE',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.teSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ti),
      abakadaTitle: 'TI',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.tiSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.to),
      abakadaTitle: 'TO',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.toSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.tu),
      abakadaTitle: 'TU',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.tuSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.wa),
      abakadaTitle: 'WA',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.waSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.we),
      abakadaTitle: 'WE',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.weSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.wi),
      abakadaTitle: 'WI',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.wiSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.wo),
      abakadaTitle: 'WO',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.woSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.wu),
      abakadaTitle: 'WU',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.wuSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ya),
      abakadaTitle: 'YA',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.yaSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.ye),
      abakadaTitle: 'YE',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.yeSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.yi),
      abakadaTitle: 'YI',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.yiSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.yo),
      abakadaTitle: 'YO',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.yoSound),
    ),
    AbakadaData(
      abakadaAsset: AssetsPath.getabakadaImage(Abakada.yu),
      abakadaTitle: 'YU',
      abakadaDescription: 'Apple',
      abakadaBG: Color.fromARGB(193, 240, 241, 170),
      abakadaSoundAsset: AssetsPath.getabakadaSound(Abakada.yuSound),
    ),
  ];

  static List<SalitaData> salitaItems = [
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.kuko),
      salitaName: 'kuko',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.kukoSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.ulo),
      salitaName: 'ulo',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.uloSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.mata),
      salitaName: 'mata',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.mataSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.paa),
      salitaName: 'paa',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.paaSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.siko),
      salitaName: 'siko',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.sikoSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.puso),
      salitaName: 'puso',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.pusoSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.labi),
      salitaName: 'labi',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.labiSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.apa),
      salitaName: 'apa',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.apaSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.kama),
      salitaName: 'kama',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.kamaSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.relo),
      salitaName: 'relo',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.reloSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.dugo),
      salitaName: 'dugo',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.dugoSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.bibe),
      salitaName: 'bibe',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.bibeSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.lobo),
      salitaName: 'lobo',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.loboSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.dila),
      salitaName: 'dila',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.dilaSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.lolo),
      salitaName: 'lolo',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.loloSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.lola),
      salitaName: 'lola',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.lolaSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.tasa),
      salitaName: 'tasa',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.tasaSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.daga),
      salitaName: 'daga',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.dagaSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.keso),
      salitaName: 'keso',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.kesoSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.buko),
      salitaName: 'buko',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.bukoSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.bote),
      salitaName: 'bote',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.boteSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.baso),
      salitaName: 'baso',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.basoSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.ate),
      salitaName: 'ate',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.ateSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.bata),
      salitaName: 'bata',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.bataSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.kuya),
      salitaName: 'kuya',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.kuyaSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.mama),
      salitaName: 'mama',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.mamaSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.misa),
      salitaName: 'misa',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.misaSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.papa),
      salitaName: 'papa',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.papaSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.toro),
      salitaName: 'toro',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.toroSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.daliri),
      salitaName: 'daliri',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.daliriSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.lababo),
      salitaName: 'lababo',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.lababoSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.pisara),
      salitaName: 'pisara',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.pisaraSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.gitara),
      salitaName: 'gitara',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.gitaraSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.modelo),
      salitaName: 'modelo',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.modeloSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.musika),
      salitaName: 'musika',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.musikaSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.payaso),
      salitaName: 'payaso',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.payasoSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.raketa),
      salitaName: 'raketa',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.raketaSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.regalo),
      salitaName: 'regalo',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.regaloSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.salapi),
      salitaName: 'salapi',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.salapiSound),
    ),
    SalitaData(
      salitaAsset: AssetsPath.getSalitaImages(Salita.butiki),
      salitaName: 'butiki',
      salitaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      salitaSound: AssetsPath.getSalitaSound(Salita.butikiSound),
    ),
  ];

  static List<PariralaData> pariralaItems = [
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.ball),
      pariralaName: 'ang bola',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.angBolaSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.rope),
      pariralaName: 'ang tali',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.ropeSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.priest),
      pariralaName: 'ang pari',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.priestSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.sack),
      pariralaName: 'sa sako',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.sackSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.pusa),
      pariralaName: 'ang pusa',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.angPusaSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.tree),
      pariralaName: 'ang puno',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.angPunoSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.aso),
      pariralaName: 'ang aso',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.angAsoSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.balloon),
      pariralaName: 'ang lobo',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.angLoboSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getSalitaImages(Salita.bibe),
      pariralaName: 'ang bibe',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.angBibeSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getSalitaImages(Salita.raketa),
      pariralaName: 'ang raketa',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.angRaketaSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPangungusapImages(Pangungusap.branchTrees),
      pariralaName: 'ang sanga',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.angSangaSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.mgaAso),
      pariralaName: 'ang mga aso',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.mgaAsoSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.balls),
      pariralaName: 'ang mga bola',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.mgaBolaSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.trees),
      pariralaName: 'ang mga puno',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.mgaPunoSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.mgaPusa),
      pariralaName: 'ang mga pusa',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.mgaPusaSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getSalitaImages(Salita.lobo),
      pariralaName: 'ang mga lobo',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.mgaLoboSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.mgaBibe),
      pariralaName: 'ang mga bibe',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.mgaBibeSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.lala),
      pariralaName: 'si Lala',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.siLalaSound),
    ),
       PariralaData(
      pariralaAsset: AssetsPath.getSalitaImages(Salita.ate),
      pariralaName: 'si Ate',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.siAteSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.nene),
      pariralaName: 'si Nene',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.neneSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getSalitaImages(Salita.lola),
      pariralaName: 'si Lola',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.siLolaSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getSalitaImages(Salita.lolo),
      pariralaName: 'si Lolo',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.siLoloSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getSalitaImages(Salita.kuya),
      pariralaName: 'si Kuya',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.siKuyaSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.sinaLolaLolo),
      pariralaName: 'sina Lola at lolo',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.sinaLolaLoloSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.sinaAteKuya),
      pariralaName: 'sina ate at kuya',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.sinaAteKuyaSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.sinaNeneLala),
      pariralaName: 'sina Nene at Lala',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.sinaNeneLalaSound),
    ),
    PariralaData(
      pariralaAsset: AssetsPath.getPariralaImages(Parirala.sinaMamaPapa),
      pariralaName: 'sina Mama at Papa',
      pariralaBackgroundColor: Color.fromARGB(193, 240, 241, 170),
      pariralaSound: AssetsPath.getPariralaSound(Parirala.sinaMamaPapaSound),
    ),
  ];

  static List<PangungusapData> pangungusapItem = [
    PangungusapData(
      pangungusapAsset: AssetsPath.getPangungusapImages(Pangungusap.Lapis),
      pangungusapName: 'Ako ay may lapis.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.lapisSound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPariralaImages(Parirala.sinaNeneLala),
      pangungusapName: 'Sina Nene at Lala ay masaya.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.neneLalaSound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPangungusapImages(Pangungusap.catDogPlay),
      pangungusapName: 'Ang aso at pusa ay naglalaro.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.catDogPlaySound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPangungusapImages(Pangungusap.pusaPuno),
      pangungusapName: 'Ang pusa ay nasa puno.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.pusaPunoSound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPangungusapImages(Pangungusap.bibeSapa),
      pangungusapName: 'Ang bibe ay nasa sapa.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.bibeSapaSound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPariralaImages(Parirala.balloon),
      pangungusapName: 'Ang lobo ay pula.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset: AssetsPath.getPangungusapSound(Pangungusap.loboRedSound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPangungusapImages(Pangungusap.ratKeso),
      pangungusapName: 'Mahilig ang daga sa keso.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.ratKesoSound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPangungusapImages(Pangungusap.butiki),
      pangungusapName: 'Ang butiki ay nasa pader.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.butikiSound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPangungusapImages(Pangungusap.saging),
      pangungusapName: 'Ang saging ay dilaw.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.sagingSound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPangungusapImages(Pangungusap.alagaPusa),
      pangungusapName: 'Ako ay may alagang pusa.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.alagangPusaSound),
    ),
    PangungusapData(
      pangungusapAsset:
          AssetsPath.getPangungusapImages(Pangungusap.branchTrees),
      pangungusapName: 'Ang sanga ay mahaba.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.branchTreesSound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPangungusapImages(Pangungusap.manika),
      pangungusapName: 'May manika ang bata.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset: AssetsPath.getPangungusapSound(Pangungusap.manikaSound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPangungusapImages(Pangungusap.akoRaketa),
      pangungusapName: 'Ako ay may raketa.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.akoRaketaSound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPangungusapImages(Pangungusap.kuyaGitara),
      pangungusapName: 'Si kuya ay may gitara.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.kuyaGitaraSound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPangungusapImages(Pangungusap.lasoRed),
      pangungusapName: 'Ang laso ay kulay pula.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.lasoRedSound),
    ),
    PangungusapData(
      pangungusapAsset: AssetsPath.getPangungusapImages(Pangungusap.ube),
      pangungusapName: 'Ang ube ay kulay lila.',
      pangungusapBG: Color.fromARGB(193, 240, 241, 170),
      pangungusapSoundAsset:
          AssetsPath.getPangungusapSound(Pangungusap.ubeLilaSound),
    ),
  ];

  static List<AlpabetoData> alpabetoItem = [
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.a),
      alpabetoTitle: 'A',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.aSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.b),
      alpabetoTitle: 'B',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.bSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.d),
      alpabetoTitle: 'D',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.dSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.e),
      alpabetoTitle: 'E',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.eSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.g),
      alpabetoTitle: 'G',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.gSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.h),
      alpabetoTitle: 'H',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.hSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.i),
      alpabetoTitle: 'I',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.iSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.k),
      alpabetoTitle: 'K',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.kSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.l),
      alpabetoTitle: 'L',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.lSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.m),
      alpabetoTitle: 'M',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.mSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.n),
      alpabetoTitle: 'N',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.nSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.ng),
      alpabetoTitle: 'NG',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.ngSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.o),
      alpabetoTitle: 'O',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.oSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.p),
      alpabetoTitle: 'P',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.pSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.r),
      alpabetoTitle: 'R',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.rSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.s),
      alpabetoTitle: 'S',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.sSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.t),
      alpabetoTitle: 'T',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.tSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.u),
      alpabetoTitle: 'U',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.uSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.w),
      alpabetoTitle: 'W',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.wSound),
    ),
    AlpabetoData(
      alpabetoAsset: AssetsPath.getAlpabetoImages(Alpabeto.y),
      alpabetoTitle: 'Y',
      alpabetoDescription: 'Apple',
      alpabetodaBG: Color.fromARGB(193, 240, 241, 170),
      alpabetoSoundAsset: AssetsPath.getAlpabetoSound(Alpabeto.ySound),
    )
  ];
}
